### ISSUE TITLE
Please update dependencies

### ISSUE THREAD

**Issue by OneFiveFour** [marcinOz/TestCoroutineRule#1]
Hi, thank you for providing this mini-but-useful lib :)

You are currently using `jetified-kotlinx-coroutines-debug-1.3.0-M1` which leads to an error message:

```
Duplicate class kotlinx.coroutines.debug.internal.DebugProbesImpl$CoroutineOwner
```

when using your lib with a bare minimum of other androidTestImplementation dependencies. 
For example:

```
// Integration Tests
androidTestImplementation 'androidx.test:runner:1.4.0'
androidTestImplementation 'com.github.marcinOz:TestCoroutineRule:1.0.1'
androidTestImplementation "com.google.dagger:hilt-android-testing:2.38.1"
kaptAndroidTest "com.google.dagger:hilt-android-compiler:2.38.1"
``` 

Updating this dependency to the current version `1.5.1` should fix this issue.

**Comment by marcinOz** [comment]
New version 1.0.2 have all dependencies updated.
